version: "3.7"

services:
  database:
    image: postgres:latest
    env_file: .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    depends_on:
      - database
    networks:
      - default
    ports:
    - "1337:1337"
volumes:
  data:
