CREATE TABLE IF NOT EXISTS slalomer(
    id VARCHAR(256) PRIMARY KEY NOT NULL UNIQUE,
    name VARCHAR(256) NOT NULL UNIQUE,
    email VARCHAR(256) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    photo VARCHAR(256),
    location VARCHAR(256)
);
